/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.myDatabaseServer;

import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.*;

/**
 *
 * @author Jermaine H. Ramsay
 */
public class AccessModify extends GlobalVariables {
    // Variables
    private String newAccessLevel;
   
    /**
     * Creates new form AccessModify
     */
    public AccessModify() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("User Access Modifier");
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblCurrentUser = new javax.swing.JLabel();
        txtCurrentUser = new javax.swing.JTextField();
        lblCurrentAccess = new javax.swing.JLabel();
        txtCurrentAccessLevel = new javax.swing.JTextField();
        lblNewAccessLevel = new javax.swing.JLabel();
        txtNewAccessLevel = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Adwaita Sans", 1, 24)); // NOI18N
        lblTitle.setText("Modify User Access");

        lblCurrentUser.setText("Current User:");

        txtCurrentUser.setEditable(false);
        txtCurrentUser.setEnabled(false);
        txtCurrentUser.setFocusable(false);

        lblCurrentAccess.setText("Current Access Level:");

        txtCurrentAccessLevel.setEditable(false);
        txtCurrentAccessLevel.setEnabled(false);
        txtCurrentAccessLevel.setFocusable(false);

        lblNewAccessLevel.setText("New Access Level:");

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(this::btnSubmitActionPerformed);

        btnReset.setText("Reset");
        btnReset.addActionListener(this::btnResetActionPerformed);

        btnExit.setText("Exit");
        btnExit.addActionListener(this::btnExitActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTitle)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnSubmit)
                            .addGap(109, 109, 109)
                            .addComponent(btnReset))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblCurrentUser, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblCurrentAccess, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblNewAccessLevel, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCurrentUser)
                                .addComponent(txtCurrentAccessLevel)
                                .addComponent(txtNewAccessLevel, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit)
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCurrentUser)
                    .addComponent(txtCurrentUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCurrentAccess)
                    .addComponent(txtCurrentAccessLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewAccessLevel)
                    .addComponent(txtNewAccessLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // Processing.
        this.setVisible(false);
        myAdministrator.setVisible(true);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // Clear Form
        txtCurrentAccessLevel.setText("");
        txtCurrentUser.setText("");
        txtNewAccessLevel.setText("");
        UserName = "";
        userAccountLevel = "";
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // Processing
        newAccessLevel = txtNewAccessLevel.getText();
        modifyInfo();
       
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // Processing.
        placeInfo();
    }//GEN-LAST:event_formWindowOpened

    
    // Functions.
    private void placeInfo() {
        txtCurrentUser.setText(UserName);
        txtCurrentAccessLevel.setText(modifyUserAccountType);
    }
    
    private void modifyInfo() {
        try {  
        databaseURL = databaseURLHeader + databaseHostName + ":" + databasePort + "/" + databaseName + secureTransport;
        databaseConn = DriverManager.getConnection(databaseURL,databaseUsername,databasePassword);
        if(databaseConn == null) {
         JOptionPane.showMessageDialog(null,"Unable to connect to Database!");
        } else {
           myPrepStmt = databaseConn.prepareStatement(modifyAccessQuery);
           myPrepStmt.setString(1, newAccessLevel);
           myPrepStmt.setString(2, UserName);
           
           int resultUpdate = myPrepStmt.executeUpdate();
           
           if(resultUpdate > 0) {
               JOptionPane.showMessageDialog(null,"Updated User Access Level");
           } else {
               JOptionPane.showMessageDialog(null,"Unable to Update Access Level!");
           }
        } // End of if-else statement for connecting to database.
      } catch (SQLException e) {
          JOptionPane.showMessageDialog(null,e.getMessage());
      }  
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel lblCurrentAccess;
    private javax.swing.JLabel lblCurrentUser;
    private javax.swing.JLabel lblNewAccessLevel;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtCurrentAccessLevel;
    private javax.swing.JTextField txtCurrentUser;
    private javax.swing.JTextField txtNewAccessLevel;
    // End of variables declaration//GEN-END:variables
}
