/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.myDatabaseServer;



import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.*;
/**
 *
 * @author Jermaine H. Ramsay
 */
public class AccountActivity extends GlobalFunctions {
    
   
    /**
     * Creates new form AccountActivity
     */
    public AccountActivity() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Account Manager");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblUserActivity = new javax.swing.JLabel();
        txtUserActivity = new javax.swing.JTextField();
        rbEnabled = new javax.swing.JRadioButton();
        rbDisabled = new javax.swing.JRadioButton();
        btnSubmit = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Adwaita Sans", 1, 24)); // NOI18N
        lblTitle.setText("Account Management");

        lblUsername.setText("Username:");

        txtUsername.setEditable(false);
        txtUsername.setEnabled(false);
        txtUsername.setFocusable(false);

        lblUserActivity.setText("User Access (Enabled/Disabled):");

        txtUserActivity.setEditable(false);
        txtUserActivity.setEnabled(false);
        txtUserActivity.setFocusable(false);

        rbEnabled.setText("Enable");
        rbEnabled.addActionListener(this::rbEnabledActionPerformed);

        rbDisabled.setText("Disable");
        rbDisabled.addActionListener(this::rbDisabledActionPerformed);

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(this::btnSubmitActionPerformed);

        btnReset.setText("Reset");
        btnReset.addActionListener(this::btnResetActionPerformed);

        btnExit.setText("Exit");
        btnExit.addActionListener(this::btnExitActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSubmit)
                        .addGap(133, 133, 133)
                        .addComponent(btnReset))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUserActivity, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblUsername, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rbEnabled, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUserActivity, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(rbDisabled))))
                    .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit)
                .addGap(117, 117, 117))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblTitle)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUserActivity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUserActivity))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbEnabled)
                    .addComponent(rbDisabled))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbEnabledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEnabledActionPerformed
        // Processing.
        if(rbEnabled.isSelected()) {
            rbDisabled.setSelected(false);
            newAccountActivity = 1;
        }
    }//GEN-LAST:event_rbEnabledActionPerformed

    private void rbDisabledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDisabledActionPerformed
        // Processing.
        if(rbDisabled.isSelected()) {
            rbEnabled.setSelected(false);
            newAccountActivity = 0;
        }
    }//GEN-LAST:event_rbDisabledActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // Processing.
        this.setVisible(false);
        myAdministrator.setVisible(true);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // Processing.
        resetForm();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // Processing.
        if(rbEnabled.isSelected()) {
            newAccountActivity = 1;
        } else if(rbDisabled.isSelected()) {
            newAccountActivity = 0;
        }
        modifyInfo();
        resetForm();
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // Processing.
        getUserAccess();
        placeInfo();
  
    }//GEN-LAST:event_formWindowOpened

    
    // Functions
    // Functions to place info.
    private void placeInfo() {
        txtUsername.setText(UserName);
        if(accountActivity == 1) {
          txtUserActivity.setText("Enabled");
          rbEnabled.setSelected(true);
          rbDisabled.setSelected(false);
        } else if(accountActivity == 0) {
          txtUserActivity.setText("Disabled");
          rbDisabled.setSelected(true);
          rbEnabled.setSelected(false);
        }
    } // End of placeinfo function
    
    // Function to reset form
    private void resetForm() {
        rbEnabled.setSelected(false);
        rbDisabled.setSelected(false);
        txtUserActivity.setText("");
        txtUsername.setText("");
        UserName = "";
        accountActivity = 9;
        newAccountActivity = 9;
    }
    // Function to modify account activity
    // Function to modify information.
    private void modifyInfo() {
         try {     
           databaseURL = databaseURLHeader + databaseHostName + ":" + databasePort + "/" + databaseName + secureTransport;
           databaseConn = DriverManager.getConnection(databaseURL, databaseUsername, databasePassword);
          if(databaseConn == null) {
            JOptionPane.showMessageDialog(null,"Unable to connect to Database!");
          } else {
             
              // Grabbing user information.
              myPrepStmt = databaseConn.prepareStatement(modifyActivityQuery);
              myPrepStmt.setString(1, Integer.toString(newAccountActivity));
              myPrepStmt.setString(2, UserName);
              
              int rowsModified = myPrepStmt.executeUpdate();
              
              if(rowsModified > 0) {
                JOptionPane.showMessageDialog(null,"User information modified!");
              } else {
                 JOptionPane.showMessageDialog(null,"Unable to modify information");
              } 
      
         } // End of if else statement to pull information using either firstname or username.  
      } catch (SQLException exception) {
         JOptionPane.showMessageDialog(null,"Exception is: " + exception.getMessage());
      } // End of try-catch
    }
    
      private void getUserAccess() {
      try {  
        databaseURL = databaseURLHeader + databaseHostName + ":" + databasePort + "/" + databaseName + secureTransport;
        databaseConn = DriverManager.getConnection(databaseURL,databaseUsername,databasePassword);
        if(databaseConn == null) {
         JOptionPane.showMessageDialog(null,"Unable to connect to Database!");
        } else {
           myPrepStmt = databaseConn.prepareStatement(checkQuery);
           myPrepStmt.setString(1, UserName);
           myResultSet = myPrepStmt.executeQuery();
           
           if(myResultSet.next()) {
               UserName = myResultSet.getString("Username");
               userAccountLevel = myResultSet.getString("AccessType");
               accountActivity = Integer.parseInt(myResultSet.getString("Active"));
           } else {
               JOptionPane.showMessageDialog(null,"User does not exist!");
           }
        } // End of if-else statement for connecting to database.
      } catch (SQLException e) {
          JOptionPane.showMessageDialog(null,e.getMessage());
      }  
        
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUserActivity;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JRadioButton rbDisabled;
    private javax.swing.JRadioButton rbEnabled;
    private javax.swing.JTextField txtUserActivity;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
