/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.myDatabaseServer;
import javax.swing.*;
/**
 *
 * @author Jermaine H. Ramsay
 */
public class AdjustedBodyWeight extends GlobalFunctions {
    
    
    /**
     * Creates new form AdjustedBodyWeight
     */
    public AdjustedBodyWeight() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Adjusted Body Weight Calculator");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPatientWeight = new javax.swing.JLabel();
        txtPatientWeight = new javax.swing.JTextField();
        rbLbs = new javax.swing.JRadioButton();
        rbKg = new javax.swing.JRadioButton();
        lblPatientHeight = new javax.swing.JLabel();
        txtPatientHeight = new javax.swing.JTextField();
        rbCM = new javax.swing.JRadioButton();
        rbInches = new javax.swing.JRadioButton();
        lblPatientIdealBW = new javax.swing.JLabel();
        txtPatientIdealBW = new javax.swing.JTextField();
        lblPatientAdjustedWeight = new javax.swing.JLabel();
        txtPatientAdjustedWeight = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        btnCalculate = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblPatientSex = new javax.swing.JLabel();
        rbMale = new javax.swing.JRadioButton();
        rbFemale = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblPatientWeight.setText("Patient Weight:");

        rbLbs.setText("in Lbs");
        rbLbs.addActionListener(this::rbLbsActionPerformed);

        rbKg.setText("in Kg");
        rbKg.addActionListener(this::rbKgActionPerformed);

        lblPatientHeight.setText("Patient Height:");

        rbCM.setText("in CM");
        rbCM.addActionListener(this::rbCMActionPerformed);

        rbInches.setText("in Inches");
        rbInches.addActionListener(this::rbInchesActionPerformed);

        lblPatientIdealBW.setText("Patient Ideal Weight:");

        txtPatientIdealBW.setEditable(false);
        txtPatientIdealBW.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPatientIdealBW.setText("0 kg");
        txtPatientIdealBW.setBorder(null);

        lblPatientAdjustedWeight.setText("Patient Adjusted Weight:");

        txtPatientAdjustedWeight.setEditable(false);
        txtPatientAdjustedWeight.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPatientAdjustedWeight.setText("0 kg");

        btnReset.setBackground(new java.awt.Color(242, 242, 242));
        btnReset.setText("Reset");
        btnReset.setBorder(null);
        btnReset.setMaximumSize(new java.awt.Dimension(54, 18));
        btnReset.setMinimumSize(new java.awt.Dimension(54, 18));
        btnReset.addActionListener(this::btnResetActionPerformed);

        btnCalculate.setBackground(new java.awt.Color(242, 242, 242));
        btnCalculate.setText("Calculate");
        btnCalculate.setBorder(null);
        btnCalculate.addActionListener(this::btnCalculateActionPerformed);

        btnExit.setBackground(new java.awt.Color(242, 242, 242));
        btnExit.setText("Exit");
        btnExit.setBorder(null);
        btnExit.addActionListener(this::btnExitActionPerformed);

        lblTitle.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        lblTitle.setText("Adjusted Body Weight Calculator");

        lblPatientSex.setText("Patient Sex:");

        rbMale.setText("Male");
        rbMale.addActionListener(this::rbMaleActionPerformed);

        rbFemale.setText("Female");
        rbFemale.addActionListener(this::rbFemaleActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPatientWeight, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPatientHeight, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPatientSex, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPatientIdealBW, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPatientAdjustedWeight, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPatientAdjustedWeight, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPatientIdealBW, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(66, 66, 66))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPatientWeight, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPatientHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbKg)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbLbs))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbCM)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbInches))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbMale)
                                .addGap(34, 34, 34)
                                .addComponent(rbFemale))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTitle)
                        .addGap(80, 80, 80)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTitle)
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatientWeight)
                    .addComponent(txtPatientWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbLbs)
                    .addComponent(rbKg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatientHeight)
                    .addComponent(txtPatientHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbInches)
                    .addComponent(rbCM))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(rbFemale)
                        .addGap(18, 18, 18)
                        .addComponent(txtPatientIdealBW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPatientSex)
                            .addComponent(rbMale))
                        .addGap(10, 10, 10)
                        .addComponent(lblPatientIdealBW)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatientAdjustedWeight)
                    .addComponent(txtPatientAdjustedWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // Reset Form.
        rbCM.setSelected(false);
        rbInches.setSelected(false);
        rbKg.setSelected(false);
        rbLbs.setSelected(false);
        rbMale.setSelected(false);
        rbFemale.setSelected(false);
        txtPatientAdjustedWeight.setText("0 kg");
        txtPatientWeight.setText("");
        txtPatientHeight.setText("");
        txtPatientIdealBW.setText("0 kg");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // Closing form.
        this.setVisible(false);
        myPharmSuite.setVisible(true);
    }//GEN-LAST:event_btnExitActionPerformed
 
    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        // Calculating CrCl.
        checkForm();
        patientWeight = Double.parseDouble(txtPatientWeight.getText());
        patientHeight = Double.parseDouble(txtPatientHeight.getText());
        if(rbCM.isSelected()) {
            patientHeight = patientHeight / cmConversion;
        }
        
        if(rbLbs.isSelected()) {
            patientWeight = patientWeight / 2.54;
        }
        
        calculateAdjustedBW();
        txtPatientIdealBW.setText(idealBWString);
        txtPatientAdjustedWeight.setText(patientAdjustedBWString);
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void rbMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMaleActionPerformed
        // Checking male
        if(rbMale.isSelected()) {
            rbFemale.setSelected(false);
            isMale = true;
        }
    }//GEN-LAST:event_rbMaleActionPerformed

    private void rbFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFemaleActionPerformed
        // checking female.
        if(rbFemale.isSelected()) {
            rbMale.setSelected(false);
            isMale = false;
        }
    }//GEN-LAST:event_rbFemaleActionPerformed

    private void rbKgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbKgActionPerformed
        // Kg.
        if(rbKg.isSelected()) {
            rbLbs.setSelected(false);
        }
            
    }//GEN-LAST:event_rbKgActionPerformed

    private void rbLbsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLbsActionPerformed
        // Lbs.
        if(rbLbs.isSelected()) {
            rbKg.setSelected(false);
           
        }
    }//GEN-LAST:event_rbLbsActionPerformed

    private void rbCMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCMActionPerformed
        // CM.
        if(rbCM.isSelected()) {
            rbInches.setSelected(false);
            
        }
    }//GEN-LAST:event_rbCMActionPerformed

    private void rbInchesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbInchesActionPerformed
        // Inches.
        if(rbInches.isSelected()) {
            rbCM.setSelected(false);
        }
    }//GEN-LAST:event_rbInchesActionPerformed

 // Checking if form is empty.
private void checkForm() {
    if(txtPatientWeight.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null,"Please enter Patient's Weight.");
    } else if(rbKg.isSelected() == false && rbLbs.isSelected() == false) {
        JOptionPane.showMessageDialog(null,"Please choose Patient's Weight units (Kg/Lbs).");
    } else if(txtPatientHeight.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null,"Please enter Patient's Height.");
    } else if(rbCM.isSelected() == false && rbInches.isSelected() == false) {
        JOptionPane.showMessageDialog(null,"Please choose Patient's Height units (CM/Inches).");
    } else if(rbMale.isSelected() == false && rbFemale.isSelected() == false) {
        JOptionPane.showMessageDialog(null,"Please choose Patient's Sex.");
    } 
} 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel lblPatientAdjustedWeight;
    private javax.swing.JLabel lblPatientHeight;
    private javax.swing.JLabel lblPatientIdealBW;
    private javax.swing.JLabel lblPatientSex;
    private javax.swing.JLabel lblPatientWeight;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JRadioButton rbCM;
    private javax.swing.JRadioButton rbFemale;
    private javax.swing.JRadioButton rbInches;
    private javax.swing.JRadioButton rbKg;
    private javax.swing.JRadioButton rbLbs;
    private javax.swing.JRadioButton rbMale;
    private javax.swing.JTextField txtPatientAdjustedWeight;
    private javax.swing.JTextField txtPatientHeight;
    private javax.swing.JTextField txtPatientIdealBW;
    private javax.swing.JTextField txtPatientWeight;
    // End of variables declaration//GEN-END:variables
}
