package com.example.myDatabaseServer;

import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Jermaine H. Ramsay
 */
public class AdministrativeForm extends GlobalFunctions {
    
  

    /**
     * Creates new form AdministrativeForm
     */
    public AdministrativeForm() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Ramil Systems Suite Administration Settings");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnAddUser = new javax.swing.JButton();
        btnModifyInfo = new javax.swing.JButton();
        btnDeleteUser = new javax.swing.JButton();
        btnChangePassword = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnModifyAccess = new javax.swing.JButton();
        btnEnableDisable = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        lblTitle.setText("Administrative Settings");

        btnAddUser.setBackground(new java.awt.Color(242, 242, 242));
        btnAddUser.setMnemonic('A');
        btnAddUser.setText("Add User");
        btnAddUser.setBorder(null);
        btnAddUser.addActionListener(this::btnAddUserActionPerformed);

        btnModifyInfo.setBackground(new java.awt.Color(242, 242, 242));
        btnModifyInfo.setMnemonic('A');
        btnModifyInfo.setText("Modify User Info");
        btnModifyInfo.setBorder(null);
        btnModifyInfo.addActionListener(this::btnModifyInfoActionPerformed);

        btnDeleteUser.setBackground(new java.awt.Color(242, 242, 242));
        btnDeleteUser.setMnemonic('A');
        btnDeleteUser.setText("Delete User");
        btnDeleteUser.setBorder(null);
        btnDeleteUser.addActionListener(this::btnDeleteUserActionPerformed);

        btnChangePassword.setBackground(new java.awt.Color(242, 242, 242));
        btnChangePassword.setMnemonic('A');
        btnChangePassword.setText("Change User Password");
        btnChangePassword.setBorder(null);
        btnChangePassword.addActionListener(this::btnChangePasswordActionPerformed);

        btnExit.setBackground(new java.awt.Color(242, 242, 242));
        btnExit.setMnemonic('A');
        btnExit.setText("Exit");
        btnExit.setBorder(null);
        btnExit.addActionListener(this::btnExitActionPerformed);

        btnModifyAccess.setBackground(new java.awt.Color(242, 242, 242));
        btnModifyAccess.setMnemonic('A');
        btnModifyAccess.setText("Modify User Access");
        btnModifyAccess.setBorder(null);
        btnModifyAccess.addActionListener(this::btnModifyAccessActionPerformed);

        btnEnableDisable.setBackground(new java.awt.Color(242, 242, 242));
        btnEnableDisable.setMnemonic('A');
        btnEnableDisable.setText("Enable/Disable Account");
        btnEnableDisable.setBorder(null);
        btnEnableDisable.addActionListener(this::btnEnableDisableActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModifyInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModifyAccess, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnableDisable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnChangePassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(179, 179, 179))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChangePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModifyInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModifyAccess, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnableDisable, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // Exit form
        this.setVisible(false);
        myPharmSuite.setVisible(true);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserActionPerformed
        // Button to add form to Add User to database.
        myAddUser = new AddUser();
        myAddUser.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAddUserActionPerformed

    private void btnDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteUserActionPerformed
        // Processing.
        UserName = JOptionPane.showInputDialog(null,"Please enter Username");
        myDeleteUser = new DeleteUser();
        myDeleteUser.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnDeleteUserActionPerformed

    private void btnChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePasswordActionPerformed
        // Processing.
        UserName = JOptionPane.showInputDialog(null,"Please enter Username!");
        myChangePassword = new ChangePassword();
        myChangePassword.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnChangePasswordActionPerformed

    private void btnModifyInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyInfoActionPerformed
        // Processing.
        UserName = JOptionPane.showInputDialog(null,"Please enter Username");
        getUser();
        ModifyUser();     
    }//GEN-LAST:event_btnModifyInfoActionPerformed

    private void btnModifyAccessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyAccessActionPerformed
        // Processing.
        UserName = JOptionPane.showInputDialog(null,"Please enter Username");
        myModifyAccess = new AccessModify();  
        myModifyAccess.setVisible(true);
        this.setVisible(false);  
    }//GEN-LAST:event_btnModifyAccessActionPerformed

    private void btnEnableDisableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnableDisableActionPerformed
        // Processing.
        UserName = JOptionPane.showInputDialog(null,"Please enter Username");
        getUser();
        myActivity = new AccountActivity();
        myActivity.setVisible(true);
    }//GEN-LAST:event_btnEnableDisableActionPerformed

    private void ModifyUser() {
        myModifyUser = new ModifyUserInfo();
        myModifyUser.setVisible(true);
        this.setVisible(false);
    }
    
    private void getUser() {
             
             // Processing to obtain user info
     try {     
           databaseURL = databaseURLHeader + databaseHostName + ":" + databasePort + "/" + databaseName + secureTransport;
           databaseConn = DriverManager.getConnection(databaseURL, databaseUsername, databasePassword);
          if(databaseConn == null) {
            JOptionPane.showMessageDialog(null,"Unable to connect to Database!");
          } else {
             
              // checking if username is available.
              myPrepStmt = databaseConn.prepareStatement(checkQuery);
              myPrepStmt.setString(1, UserName);
              myResultSet = myPrepStmt.executeQuery();
              
              if(myResultSet.next()) {
                 // Getting user info from database.
                 DatabaseuserFirstName = myResultSet.getString("Firstname");
                 DatabaseuserLastName = myResultSet.getString("Lastname");
                 DatabaseuserBirthday = myResultSet.getString("Birthday");
                 DatabaseuserAge = myResultSet.getInt("Age");
                 DatabaseuserEmailAddress = myResultSet.getString("EmailAddress");
                 DatabaseloginUsername = myResultSet.getString("Username");
              } else {
                 JOptionPane.showMessageDialog(null,"User not found!");
              } 
      
         } // End of if else statement to pull information using either firstname or username.  
      } catch (SQLException exception) {
         JOptionPane.showMessageDialog(null,"Exception is: " + exception.getMessage());
      } // End of try-catch
    }
    
   // End of function getAccess.
   
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JButton btnDeleteUser;
    private javax.swing.JButton btnEnableDisable;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnModifyAccess;
    private javax.swing.JButton btnModifyInfo;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
