package com.example.myDatabaseServer;
import javax.swing.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Jermaine H. Ramsay
 */
public class CalciumCorrectionForm extends GlobalFunctions {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CalciumCorrectionForm.class.getName());

    /**
     * Creates new form CalciumCorrectionForm
     */
    public CalciumCorrectionForm() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Calcium Correction Calculator");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblSCalciumLevel = new javax.swing.JLabel();
        lblSAlbuminLevel = new javax.swing.JLabel();
        lblNormalAlbumin = new javax.swing.JLabel();
        txtSerumAlbumin = new javax.swing.JTextField();
        txtSerumCalcium = new javax.swing.JTextField();
        lblNormalAlbuminlevel = new javax.swing.JLabel();
        lblCorrectedCalcium = new javax.swing.JLabel();
        txtCorrectedCalcium = new javax.swing.JTextField();
        btnCalculate = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblTitle.setFont(new java.awt.Font("Adwaita Sans", 1, 24)); // NOI18N
        lblTitle.setText("Calcium Correction Calculator");

        lblSCalciumLevel.setText("Serum Calcium Level (in mg/dL):");

        lblSAlbuminLevel.setText("Serum Albumin Level (in g/dL):");

        lblNormalAlbumin.setText("Normal Albumin:");

        lblNormalAlbuminlevel.setText("4 g/dL");

        lblCorrectedCalcium.setText("Corrected Calcium (in mg/dL):");

        txtCorrectedCalcium.setEditable(false);

        btnCalculate.setText("Calculate");
        btnCalculate.addActionListener(this::btnCalculateActionPerformed);

        btnReset.setText("Reset");
        btnReset.addActionListener(this::btnResetActionPerformed);

        btnExit.setText("Exit");
        btnExit.addActionListener(this::btnExitActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSCalciumLevel, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                            .addComponent(lblSAlbuminLevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNormalAlbumin)
                                    .addComponent(lblCorrectedCalcium))
                                .addGap(16, 16, 16)))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSerumCalcium, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                            .addComponent(txtSerumAlbumin)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNormalAlbuminlevel)
                                .addGap(191, 191, 191))
                            .addComponent(txtCorrectedCalcium)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSCalciumLevel)
                    .addComponent(txtSerumCalcium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSAlbuminLevel)
                    .addComponent(txtSerumAlbumin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNormalAlbumin)
                    .addComponent(lblNormalAlbuminlevel))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorrectedCalcium)
                    .addComponent(txtCorrectedCalcium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // Button to clear full form.
        txtCorrectedCalcium.setText("");
        txtSerumAlbumin.setText("");
        txtSerumCalcium.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // Exit form.
        this.setVisible(false);
        myPharmSuite.setVisible(true);
        
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        // Calculating corrected calcium
          // Checking if the form has been filled out.
           if(txtSerumCalcium.getText().isEmpty()) {
             JOptionPane.showMessageDialog(null,"Please enter Patient's Serum Calcium level.  Thank you.");
           } else if(txtSerumAlbumin.getText().isEmpty()) {
             JOptionPane.showMessageDialog(null, "Please enter Patient's Serum Albumin level.  Thank you.");
           } else {
            serumCalcium = Double.parseDouble(txtSerumCalcium.getText());
            serumAlbumin = Double.parseDouble(txtSerumAlbumin.getText());
            correctedCalcium();
            correctedCalciumString = String.format("%.2f", correctedCalcium);
            txtCorrectedCalcium.setText(correctedCalciumString);
          } // End of if-elseif statement
    }//GEN-LAST:event_btnCalculateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel lblCorrectedCalcium;
    private javax.swing.JLabel lblNormalAlbumin;
    private javax.swing.JLabel lblNormalAlbuminlevel;
    private javax.swing.JLabel lblSAlbuminLevel;
    private javax.swing.JLabel lblSCalciumLevel;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtCorrectedCalcium;
    private javax.swing.JTextField txtSerumAlbumin;
    private javax.swing.JTextField txtSerumCalcium;
    // End of variables declaration//GEN-END:variables
}
