/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.myDatabaseServer;
import javax.swing.*;

/**
 *
 * @author Jermaine H. Ramsay
 */
public class CrClCalculator extends GlobalFunctions {
    

    /**
     * Creates new form CrClCalculator
     */
    public CrClCalculator() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Renal Function Calculator");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblPatientAge = new javax.swing.JLabel();
        txtPatientAge = new javax.swing.JTextField();
        lblPatientSCr = new javax.swing.JLabel();
        txtPatientSCr = new javax.swing.JTextField();
        lblPatientSex = new javax.swing.JLabel();
        rbMale = new javax.swing.JRadioButton();
        rbFemale = new javax.swing.JRadioButton();
        lblPatientWeight = new javax.swing.JLabel();
        txtPatientWeight = new javax.swing.JTextField();
        rbKg = new javax.swing.JRadioButton();
        rbLbs = new javax.swing.JRadioButton();
        lblPatientHeight = new javax.swing.JLabel();
        txtPatientHeight = new javax.swing.JTextField();
        rbCM = new javax.swing.JRadioButton();
        rbInches = new javax.swing.JRadioButton();
        lblPatientCrCl = new javax.swing.JLabel();
        txtPatientCrCl = new javax.swing.JTextField();
        btnCalculate = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        lblTitle.setText("Renal Function Calculator");

        lblPatientAge.setText("Patient Age:");

        lblPatientSCr.setText("Patient SCr:");

        lblPatientSex.setText("Patient Sex:");

        rbMale.setText("Male");
        rbMale.addActionListener(this::rbMaleActionPerformed);

        rbFemale.setText("Female");
        rbFemale.addActionListener(this::rbFemaleActionPerformed);

        lblPatientWeight.setText("Patient Weight:");

        rbKg.setText("in Kg");
        rbKg.addActionListener(this::rbKgActionPerformed);

        rbLbs.setText("in lbs");
        rbLbs.addActionListener(this::rbLbsActionPerformed);

        lblPatientHeight.setText("Patient Height:");

        rbCM.setText("in CM");
        rbCM.addActionListener(this::rbCMActionPerformed);

        rbInches.setText("in Inches");
        rbInches.addActionListener(this::rbInchesActionPerformed);

        lblPatientCrCl.setText("Patient CrCl (in mL/min):");

        txtPatientCrCl.setEditable(false);
        txtPatientCrCl.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPatientCrCl.setText("0 mL/min");
        txtPatientCrCl.setBorder(null);

        btnCalculate.setText("Calculate");
        btnCalculate.setBorder(null);
        btnCalculate.addActionListener(this::btnCalculateActionPerformed);

        btnReset.setText("Reset");
        btnReset.setBorder(null);
        btnReset.addActionListener(this::btnResetActionPerformed);

        btnExit.setText("Exit");
        btnExit.setBorder(null);
        btnExit.addActionListener(this::btnExitActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPatientHeight)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPatientHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rbCM)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbInches))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(156, 156, 156)
                                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPatientAge)
                                    .addComponent(lblPatientSex))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(txtPatientAge, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(rbMale)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbFemale)))
                                .addGap(70, 70, 70)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPatientSCr)
                                    .addComponent(lblPatientWeight))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPatientSCr, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                    .addComponent(txtPatientWeight))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbKg)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbLbs))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(lblPatientCrCl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPatientCrCl, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(lblTitle)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatientAge)
                    .addComponent(txtPatientAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPatientSCr)
                    .addComponent(txtPatientSCr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatientSex)
                    .addComponent(rbMale)
                    .addComponent(rbFemale)
                    .addComponent(lblPatientWeight)
                    .addComponent(txtPatientWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbKg)
                    .addComponent(rbLbs))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatientHeight)
                    .addComponent(txtPatientHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbCM)
                    .addComponent(rbInches))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatientCrCl)
                    .addComponent(txtPatientCrCl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // Button to reset form.
        txtPatientAge.setText("");
        txtPatientCrCl.setText("0 mL/min");
        txtPatientSCr.setText("");
        txtPatientHeight.setText("");
        txtPatientWeight.setText("");
        rbCM.setSelected(false);
        rbInches.setSelected(false);
        rbKg.setSelected(false);
        rbLbs.setSelected(false);
        rbMale.setSelected(false);
        rbFemale.setSelected(false);
    }//GEN-LAST:event_btnResetActionPerformed

    private void rbMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMaleActionPerformed
        // setting Male rb is the only one selected.
        if(rbMale.isSelected() == true) {
            rbFemale.setSelected(false);
        }
    }//GEN-LAST:event_rbMaleActionPerformed

    private void rbFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFemaleActionPerformed
        // setting Female rb is the only one selected.
        if(rbFemale.isSelected() == true) {
            rbMale.setSelected(false);
        }
    }//GEN-LAST:event_rbFemaleActionPerformed

    private void rbKgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbKgActionPerformed
        // setting Kg is only selected
        if(rbKg.isSelected() == true) {
            rbLbs.setSelected(false);
        }
    }//GEN-LAST:event_rbKgActionPerformed

    private void rbLbsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLbsActionPerformed
        // setting lb is only selected
        if(rbLbs.isSelected() == true) {
            rbKg.setSelected(false);
        }
    }//GEN-LAST:event_rbLbsActionPerformed

    private void rbCMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCMActionPerformed
        // CM Radiobutton
        if(rbCM.isSelected() == true) {
            rbInches.setSelected(false);
        }
    }//GEN-LAST:event_rbCMActionPerformed

    private void rbInchesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbInchesActionPerformed
        // Inches Radio Button
        if(rbInches.isSelected() == true) {
            rbCM.setSelected(false);
        }
    }//GEN-LAST:event_rbInchesActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        // Calculating Patient CrCl.
        checkEmpty();
        getInfo();
         if(rbMale.isSelected() == true) {
            isMale = true;
        } else {
            isMale = false;
        }
         
        if(rbCM.isSelected() == true) {
           patientHeight = patientHeight / cmConversion;   
        }
        
        if(rbLbs.isSelected() == true) {
           patientWeight = patientWeight / 2.2;
        }
        calculateCrCl();
       
        txtPatientCrCl.setText(patientCrClString + " mL/min");
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
       // Exit Form
       this.setVisible(false);
       myPharmSuite.setVisible(true);
    }//GEN-LAST:event_btnExitActionPerformed

    
// Function to obtain information from Form.
  private void getInfo() {
    // Processing.
    patientAge = Integer.parseInt(txtPatientAge.getText());
    patientWeight = Double.parseDouble(txtPatientWeight.getText());
    patientHeight = Double.parseDouble(txtPatientHeight.getText());
    patientSCr = Double.parseDouble(txtPatientSCr.getText());
  } // end of getInfo function.
  
  // Function to check if form is empty.
  private void checkEmpty() {
      if(rbCM.isSelected() == false && rbInches.isSelected() == false) {
          JOptionPane.showMessageDialog(null,"Please choose unit of Patient's Height");
      } else if(rbMale.isSelected() == false && rbFemale.isSelected() == false) {
          JOptionPane.showMessageDialog(null,"Please choose Patient's Sex");
      } else if(rbKg.isSelected() == false && rbLbs.isSelected() == false) {
          JOptionPane.showMessageDialog(null,"Please choose unit for Patient's Weight");
      } else if(txtPatientAge.getText().isEmpty()) {
          JOptionPane.showMessageDialog(null,"Please enter Patient's Age");
      } else if(txtPatientWeight.getText().isEmpty()) {
          JOptionPane.showMessageDialog(null,"Please enter Patient's Weight");
      } else if(txtPatientHeight.getText().isEmpty()) {
          JOptionPane.showMessageDialog(null,"Please enter Patient's Height");
      } else if(txtPatientSCr.getText().isEmpty()) {
          JOptionPane.showMessageDialog(null, "Please enter Patient's Serum Creatinine");
      } else {
          getInfo();
      }
             
  }
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel lblPatientAge;
    private javax.swing.JLabel lblPatientCrCl;
    private javax.swing.JLabel lblPatientHeight;
    private javax.swing.JLabel lblPatientSCr;
    private javax.swing.JLabel lblPatientSex;
    private javax.swing.JLabel lblPatientWeight;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JRadioButton rbCM;
    private javax.swing.JRadioButton rbFemale;
    private javax.swing.JRadioButton rbInches;
    private javax.swing.JRadioButton rbKg;
    private javax.swing.JRadioButton rbLbs;
    private javax.swing.JRadioButton rbMale;
    private javax.swing.JTextField txtPatientAge;
    private javax.swing.JTextField txtPatientCrCl;
    private javax.swing.JTextField txtPatientHeight;
    private javax.swing.JTextField txtPatientSCr;
    private javax.swing.JTextField txtPatientWeight;
    // End of variables declaration//GEN-END:variables
}
