package com.example.myDatabaseServer;

import javax.swing.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Jermaine H. Ramsay
 */
public class DeleteUser extends GlobalFunctions {
    
    /**
     * Creates new form AddUser
     */
    public DeleteUser() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Delete User");
        getUser.start();
        placeInfo();
        this.getRootPane().setDefaultButton(btnDeleteUser);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblUsersEmailAddress = new javax.swing.JLabel();
        lblUsersBirthday = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        btnDeleteUser = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtEmailAddress = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        txtBirthday = new javax.swing.JFormattedTextField();
        lblTitle = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        MBMainMenu = new javax.swing.JMenuBar();
        MMFile = new javax.swing.JMenu();
        MMFileUserSearch = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblFirstName.setText("First Name:");

        lblLastName.setText("Last Name:");

        lblUsersEmailAddress.setText("Email Address:");

        lblUsersBirthday.setText("Birthday:");

        lblUsername.setText("Username:");

        btnDeleteUser.setText("Delete User");
        btnDeleteUser.addActionListener(this::btnDeleteUserActionPerformed);

        btnReset.setText("Reset");
        btnReset.addActionListener(this::btnResetActionPerformed);

        btnExit.setText("Close");
        btnExit.addActionListener(this::btnExitActionPerformed);

        txtFirstName.setEditable(false);
        txtFirstName.setEnabled(false);

        txtLastName.setEditable(false);
        txtLastName.setEnabled(false);

        txtEmailAddress.setEditable(false);
        txtEmailAddress.setEnabled(false);

        txtUsername.setEditable(false);
        txtUsername.setEnabled(false);

        txtBirthday.setEditable(false);
        txtBirthday.setText("MM/DD/YYYY");
        txtBirthday.setEnabled(false);
        txtBirthday.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBirthdayFocusGained(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        lblTitle.setText("Delete User");

        lblAge.setText("Age:");

        txtAge.setEditable(false);
        txtAge.setEnabled(false);

        MMFile.setText("File");

        MMFileUserSearch.setText("User Search");
        MMFile.add(MMFileUserSearch);

        MBMainMenu.add(MMFile);

        setJMenuBar(MBMainMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(lblTitle)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(360, 360, 360)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnDeleteUser)
                        .addContainerGap(408, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFirstName)
                    .addComponent(lblLastName)
                    .addComponent(lblUsersEmailAddress)
                    .addComponent(lblUsersBirthday)
                    .addComponent(lblUsername)
                    .addComponent(lblAge))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsername)
                    .addComponent(txtBirthday, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                    .addComponent(txtEmailAddress)
                    .addComponent(txtLastName)
                    .addComponent(txtAge, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblTitle)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLastName))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUsersEmailAddress))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUsersBirthday)))
                    .addComponent(lblFirstName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAge)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsername)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // Closing form.
        this.setVisible(false);
        myPharmSuite.setVisible(true);
    }//GEN-LAST:event_btnExitActionPerformed

    private void txtBirthdayFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBirthdayFocusGained
        // function to select everything once focus gained.
        SwingUtilities.invokeLater(() -> txtBirthday.selectAll());
    }//GEN-LAST:event_txtBirthdayFocusGained

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // Button to reset Form.
        clearForm();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteUserActionPerformed
        // Function to add user.
        DeleteInfo();
        clearForm();
    }//GEN-LAST:event_btnDeleteUserActionPerformed
  
    
    // Functions.
     // Function to get information.
    private void placeInfo() {
        JOptionPane.showMessageDialog(null,DatabaseuserLastName);
        txtFirstName.setText(DatabaseuserFirstName);
        txtLastName.setText(DatabaseuserLastName);
        txtEmailAddress.setText(DatabaseuserEmailAddress);
        txtBirthday.setText(DatabaseuserBirthday);
        txtAge.setText(Integer.toString(DatabaseuserAge));
        txtUsername.setText(DatabaseloginUsername);
       
    } // End of function to get Info. 
    
    
    
    // function to clear info.
    private void clearForm() {
        txtBirthday.setText("MM/DD/YYYY");
        txtFirstName.setText("");
        txtLastName.setText("");
        txtEmailAddress.setText("");
        txtUsername.setText("");
        txtAge.setText("");
    } // End of function to clear form. 
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MBMainMenu;
    private javax.swing.JMenu MMFile;
    private javax.swing.JMenuItem MMFileUserSearch;
    private javax.swing.JButton btnDeleteUser;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblUsersBirthday;
    private javax.swing.JLabel lblUsersEmailAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JFormattedTextField txtBirthday;
    private javax.swing.JTextField txtEmailAddress;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
