/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.myDatabaseServer;

/**
 *
 * @author Jermaine H. Ramsay
 */
public class IdealBodyWeight extends GlobalFunctions {
    

    /**
     * Creates new form IdealBodyWeight
     */
    public IdealBodyWeight() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Ideal Body Weight");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblPatientHeight = new javax.swing.JLabel();
        txtPatientHeight = new javax.swing.JTextField();
        rbCM = new javax.swing.JRadioButton();
        rbInches = new javax.swing.JRadioButton();
        btnExit = new javax.swing.JButton();
        lblIdealBodyWeight = new javax.swing.JLabel();
        txtIdealBodyWeight = new javax.swing.JTextField();
        btnCalculate = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        lblPatientSex = new javax.swing.JLabel();
        rbMale = new javax.swing.JRadioButton();
        rbFemale = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        lblTitle.setText("Ideal Body Weight Calculator");

        lblPatientHeight.setText("Patient Height:");

        rbCM.setText("in CM");
        rbCM.addActionListener(this::rbCMActionPerformed);

        rbInches.setText("in Inches");
        rbInches.addActionListener(this::rbInchesActionPerformed);

        btnExit.setBackground(new java.awt.Color(242, 242, 242));
        btnExit.setText("Exit");
        btnExit.setBorder(null);
        btnExit.addActionListener(this::btnExitActionPerformed);

        lblIdealBodyWeight.setText("Patient's Ideal Body Weight (in Kg):");

        txtIdealBodyWeight.setEditable(false);
        txtIdealBodyWeight.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIdealBodyWeight.setText("0 kg");
        txtIdealBodyWeight.setBorder(null);

        btnCalculate.setBackground(new java.awt.Color(242, 242, 242));
        btnCalculate.setText("Calculate");
        btnCalculate.setBorder(null);
        btnCalculate.addActionListener(this::btnCalculateActionPerformed);

        btnReset.setBackground(new java.awt.Color(242, 242, 242));
        btnReset.setText("Reset");
        btnReset.setBorder(null);
        btnReset.addActionListener(this::btnResetActionPerformed);

        lblPatientSex.setText("Patient's Sex:");

        rbMale.setText("Male");
        rbMale.addActionListener(this::rbMaleActionPerformed);

        rbFemale.setText("Female");
        rbFemale.addActionListener(this::rbFemaleActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblIdealBodyWeight)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPatientHeight)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPatientSex)
                                    .addComponent(txtPatientHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdealBodyWeight)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbCM)
                                    .addComponent(rbMale))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbFemale)
                                    .addComponent(rbInches))))))
                .addContainerGap(181, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addGap(121, 121, 121))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatientHeight)
                    .addComponent(txtPatientHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbCM)
                    .addComponent(rbInches))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatientSex)
                    .addComponent(rbMale)
                    .addComponent(rbFemale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdealBodyWeight)
                    .addComponent(txtIdealBodyWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // Exit form.
        this.setVisible(false);
        myPharmSuite.setVisible(true);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
       // Button to reset Form.
       rbCM.setSelected(false);
       rbInches.setSelected(false);
       txtPatientHeight.setText("");
       txtIdealBodyWeight.setText("0 kg");
       rbMale.setSelected(false);
       rbFemale.setSelected(false);
    }//GEN-LAST:event_btnResetActionPerformed

    private void rbCMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCMActionPerformed
        // Process button.
        if(rbCM.isSelected() == true) {
            rbInches.setSelected(false);
        }
    }//GEN-LAST:event_rbCMActionPerformed

    private void rbInchesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbInchesActionPerformed
        // Process button.
        if(rbInches.isSelected() == true) {
            rbCM.setSelected(false);
        }
    }//GEN-LAST:event_rbInchesActionPerformed

    private void rbMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMaleActionPerformed
        // Processing.
        if(rbMale.isSelected() == true) {
            rbFemale.setSelected(false);
            isMale = true;
        }
    }//GEN-LAST:event_rbMaleActionPerformed

    private void rbFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFemaleActionPerformed
        // Processing.
        if(rbFemale.isSelected() == true) {
            rbMale.setSelected(false);
            isMale = false;
        }
    }//GEN-LAST:event_rbFemaleActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        // Calculating idealBW
        patientHeight = Double.parseDouble(txtPatientHeight.getText());
        if(rbCM.isSelected() == true) {
            patientHeight = patientHeight / cmConversion;
        }
        calculateIdealBW();
        txtIdealBodyWeight.setText(idealBWString + " kg");
    }//GEN-LAST:event_btnCalculateActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel lblIdealBodyWeight;
    private javax.swing.JLabel lblPatientHeight;
    private javax.swing.JLabel lblPatientSex;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JRadioButton rbCM;
    private javax.swing.JRadioButton rbFemale;
    private javax.swing.JRadioButton rbInches;
    private javax.swing.JRadioButton rbMale;
    private javax.swing.JTextField txtIdealBodyWeight;
    private javax.swing.JTextField txtPatientHeight;
    // End of variables declaration//GEN-END:variables
}
