
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.example.myDatabaseServer;

import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.*;

/**
 *
 * @author Jermaine H. Ramsay
 */
public class ModifyUserInfo extends GlobalFunctions {
    
    /**
     * Creates new form AddUser
     */
    public ModifyUserInfo() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Modify User Info");
        placeInfo();
        this.getRootPane().setDefaultButton(btnModifyInfo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblUsersEmailAddress = new javax.swing.JLabel();
        lblUsersBirthday = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        btnModifyInfo = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtEmailAddress = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        txtBirthday = new javax.swing.JFormattedTextField();
        lblTitle = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblFirstName.setText("First Name:");

        lblLastName.setText("Last Name:");

        lblUsersEmailAddress.setText("Email Address:");

        lblUsersBirthday.setText("Birthday:");

        lblUsername.setText("Username:");

        btnModifyInfo.setText("Modify Info");
        btnModifyInfo.addActionListener(this::btnModifyInfoActionPerformed);

        btnReset.setText("Reset");
        btnReset.addActionListener(this::btnResetActionPerformed);

        btnExit.setText("Close");
        btnExit.addActionListener(this::btnExitActionPerformed);

        txtUsername.setEditable(false);
        txtUsername.setEnabled(false);
        txtUsername.setFocusable(false);

        txtBirthday.setText("MM/DD/YYYY");
        txtBirthday.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBirthdayFocusGained(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        lblTitle.setText("Modify User Info");

        lblAge.setText("Age:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(360, 360, 360)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnModifyInfo)
                        .addContainerGap(414, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblFirstName)
                            .addComponent(lblLastName)
                            .addComponent(lblUsersEmailAddress)
                            .addComponent(lblUsersBirthday)
                            .addComponent(lblUsername)
                            .addComponent(lblAge))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUsername)
                            .addComponent(txtBirthday, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                            .addComponent(txtEmailAddress)
                            .addComponent(txtLastName)
                            .addComponent(txtAge, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(lblTitle)))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTitle)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLastName))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUsersEmailAddress))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUsersBirthday)))
                    .addComponent(lblFirstName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAge)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsername)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModifyInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // Closing form.
        this.setVisible(false);
        myAdministrator.setVisible(true);
        clearForm();
    }//GEN-LAST:event_btnExitActionPerformed

    private void txtBirthdayFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBirthdayFocusGained
        // function to select everything once focus gained.
        SwingUtilities.invokeLater(() -> txtBirthday.selectAll());
    }//GEN-LAST:event_txtBirthdayFocusGained

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // Button to reset Form.
         clearForm();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnModifyInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyInfoActionPerformed
        // Function to add user.
        isEmpty();
        getInfo();
        modifyInfo();
    }//GEN-LAST:event_btnModifyInfoActionPerformed
  
    
    // Functions.
     // Function to get information.
    private void getInfo() {
        userFirstName = txtFirstName.getText();
        userLastName = txtLastName.getText();
        userAge = Integer.parseInt(txtAge.getText());
        userBirthday = txtBirthday.getText();
        userEmailAddress = txtEmailAddress.getText();
        UserName = txtUsername.getText();

    } // End of function to get Info. 
    
    // Function to check if form is empty.
    private void isEmpty() {
        if(txtFirstName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null,"Please enter First Name!");
        } else if(txtLastName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null,"Please enter Last Name!");
        } else if(txtEmailAddress.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null,"Please enter Email Address!");
        } else if(txtBirthday.getText().equalsIgnoreCase("MM/DD/YYYY") || txtBirthday.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null,"Please enter Birthday!");
        } else if(txtAge.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null,"Please enter Age!");
        } else if(txtUsername.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null,"Please enter Username!");
        } 
    } // end of function to check if empty.
  
    // Function to clear form.
    private void clearForm() {
        txtBirthday.setText("MM/DD/YYYY");
        txtFirstName.setText("");
        txtLastName.setText("");
        txtEmailAddress.setText("");
        txtUsername.setText("");
        txtAge.setText("");
        userFirstName = "";
        userLastName = "";
        userBirthday = "";
        userAge = Integer.parseInt("");
        userEmailAddress = "";
        UserName = "";
        userAccountLevel = "";
    } // end of function to clear form. 

    
     // Function to get information.
    private void placeInfo() {
        txtFirstName.setText(DatabaseuserFirstName);
        txtLastName.setText(DatabaseuserLastName);
        txtEmailAddress.setText(DatabaseuserEmailAddress);
        txtBirthday.setText(DatabaseuserBirthday);
        txtAge.setText(Integer.toString(DatabaseuserAge));
        txtUsername.setText(DatabaseloginUsername);
       
    } // End of function to get Info. 
    
    
    // Function to modify information.
    private void modifyInfo() {
         try {     
           databaseURL = databaseURLHeader + databaseHostName + ":" + databasePort + "/" + databaseName + secureTransport;
           databaseConn = DriverManager.getConnection(databaseURL, databaseUsername, databasePassword);
          if(databaseConn == null) {
            JOptionPane.showMessageDialog(null,"Unable to connect to Database!");
          } else {
             
              // checking if username is available.
              myPrepStmt = databaseConn.prepareStatement(modifyQuery);
              myPrepStmt.setString(1, userFirstName);
              myPrepStmt.setString(2, userLastName);
              myPrepStmt.setString(3, Integer.toString(userAge));
              myPrepStmt.setString(4, userBirthday);
              myPrepStmt.setString(5, userEmailAddress);
              myPrepStmt.setString(6, UserName);
   
    
              
              int rowsModified = myPrepStmt.executeUpdate();
              
              if(rowsModified > 0) {
                JOptionPane.showMessageDialog(null,"User information modified!");
              } else {
                 JOptionPane.showMessageDialog(null,"Unable to modify information");
              } 
      
         } // End of if else statement to pull information using either firstname or username.  
      } catch (SQLException exception) {
         JOptionPane.showMessageDialog(null,"Exception is: " + exception.getMessage());
      } // End of try-catch
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnModifyInfo;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblUsersBirthday;
    private javax.swing.JLabel lblUsersEmailAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JFormattedTextField txtBirthday;
    private javax.swing.JTextField txtEmailAddress;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
