/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.myDatabaseServer;

import javax.swing.JOptionPane;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.UIManager;

public class myDatabaseServerMain extends GlobalFunctions {
    public static void main(String[] args) {
         // Look and feel statement
        try {
          for(LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
              if("GTK+".equals(info.getName())) {
                  UIManager.setLookAndFeel(info.getClassName());
                  break;
              }
          }
        } catch (Exception ex) {
          JOptionPane.showMessageDialog(null, "Exception: " + ex.getMessage());
        } // End of look and feel try-catch statement
       
         checkPropFile();
         if(fileExists == false) {
             myConfigForm.setVisible(true);
         } else {
             readConfigThread.start();
             myLoginForm.setVisible(true);
         } // End of if-else 
        
    }
}
