/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.myDatabaseServer;
import javax.swing.*;

/**
 *
 * @author Jermaine H. Ramsay
 */
public class PharmacySuiteMainMenu extends GlobalFunctions {

    /**
     * Creates new form PharmacySuiteGUI
     */
    public PharmacySuiteMainMenu() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Ramil Systems Pharmacy Suite " + currentVersion);
        lblTitle.setText("Welcome " + userFirstName);
        
        // Addition of administrative settings for the admin level users. 
        if(isAdministrator == true) {
            MMFileAdminSettings.setVisible(true);
        } else {
            MMFileAdminSettings.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCalciumCalculator = new javax.swing.JButton();
        btnCrClCalculator = new javax.swing.JButton();
        btnIBWCalculator = new javax.swing.JButton();
        btnABWCalculator = new javax.swing.JButton();
        btnVancCalculator = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        MBMainMenu = new javax.swing.JMenuBar();
        MMFile = new javax.swing.JMenu();
        MMFileAdminSettings = new javax.swing.JMenuItem();
        MMFileExit = new javax.swing.JMenuItem();
        MMHelp = new javax.swing.JMenu();
        MMHelpAbout = new javax.swing.JMenuItem();
        MMHelpUpdates = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        btnCalciumCalculator.setText("Calcium Correction Calculator");
        btnCalciumCalculator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalciumCalculatorActionPerformed(evt);
            }
        });

        btnCrClCalculator.setText("Creatinine Clearance Calculator");
        btnCrClCalculator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrClCalculatorActionPerformed(evt);
            }
        });

        btnIBWCalculator.setText("Ideal Body Weight Calculator");
        btnIBWCalculator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIBWCalculatorActionPerformed(evt);
            }
        });

        btnABWCalculator.setText("Adjusted Body Weight Calculator");
        btnABWCalculator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnABWCalculatorActionPerformed(evt);
            }
        });

        btnVancCalculator.setText("Vancomycin Dosing Calculator");
        btnVancCalculator.setEnabled(false);

        btnLogout.setBackground(new java.awt.Color(242, 242, 242));
        btnLogout.setMnemonic('x');
        btnLogout.setText("Logout");
        btnLogout.setBorder(null);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblTitle.setText("Welcome");

        MMFile.setText("File");

        MMFileAdminSettings.setText("Administrative Settings");
        MMFileAdminSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MMFileAdminSettingsActionPerformed(evt);
            }
        });
        MMFile.add(MMFileAdminSettings);

        MMFileExit.setText("Exit");
        MMFileExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MMFileExitActionPerformed(evt);
            }
        });
        MMFile.add(MMFileExit);

        MBMainMenu.add(MMFile);

        MMHelp.setText("Help");

        MMHelpAbout.setText("About");
        MMHelpAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MMHelpAboutActionPerformed(evt);
            }
        });
        MMHelp.add(MMHelpAbout);

        MMHelpUpdates.setText("Updates");
        MMHelpUpdates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MMHelpUpdatesActionPerformed(evt);
            }
        });
        MMHelp.add(MMHelpUpdates);

        MBMainMenu.add(MMHelp);

        setJMenuBar(MBMainMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCalciumCalculator, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCrClCalculator, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVancCalculator, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnIBWCalculator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnABWCalculator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36))
            .addGroup(layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTitle)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalciumCalculator, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIBWCalculator, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnABWCalculator, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrClCalculator, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnVancCalculator, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // Button to logout.
        myLoginForm.setVisible(true);
        this.setVisible(false);
        logout();
        
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void MMFileExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MMFileExitActionPerformed
        // Alternate button to close app.
        System.exit(0);
    }//GEN-LAST:event_MMFileExitActionPerformed

    private void MMHelpAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MMHelpAboutActionPerformed
        // Will display info about who made app. 
        JOptionPane.showMessageDialog(null,"Ramil Systems Suite " + appVersion + "\nCreated by: Jermaine H. Ramsay\nCreated on: 04/20/2026.");
    }//GEN-LAST:event_MMHelpAboutActionPerformed

    private void MMFileAdminSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MMFileAdminSettingsActionPerformed
        // Will allow changes to be made to access.
        myAdministrator = new AdministrativeForm();
        myAdministrator.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MMFileAdminSettingsActionPerformed

    private void btnCalciumCalculatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalciumCalculatorActionPerformed
        // To open calcium correction calculator
        myCalciumCorrection.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCalciumCalculatorActionPerformed

    private void btnIBWCalculatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIBWCalculatorActionPerformed
        // To open Ideal Body Weight Calculator.
        myIdealBodyWeight.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnIBWCalculatorActionPerformed

    private void MMHelpUpdatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MMHelpUpdatesActionPerformed
        // Checking for updates.
        myUpdates = new ProgramUpdates();
        this.setVisible(false);
        myUpdates.setVisible(true);
    }//GEN-LAST:event_MMHelpUpdatesActionPerformed

    private void btnCrClCalculatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrClCalculatorActionPerformed
       // Renal Function calculator.
       this.setVisible(false);
       renalCalculator.setVisible(true);
    }//GEN-LAST:event_btnCrClCalculatorActionPerformed

    private void btnABWCalculatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnABWCalculatorActionPerformed
        // Adjusted Body Weight Calculator.
        this.setVisible(false);
        myAdjustedBWCalc.setVisible(true);
    }//GEN-LAST:event_btnABWCalculatorActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MBMainMenu;
    private javax.swing.JMenu MMFile;
    private javax.swing.JMenuItem MMFileAdminSettings;
    private javax.swing.JMenuItem MMFileExit;
    private javax.swing.JMenu MMHelp;
    private javax.swing.JMenuItem MMHelpAbout;
    private javax.swing.JMenuItem MMHelpUpdates;
    private javax.swing.JButton btnABWCalculator;
    private javax.swing.JButton btnCalciumCalculator;
    private javax.swing.JButton btnCrClCalculator;
    private javax.swing.JButton btnIBWCalculator;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnVancCalculator;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
