package com.example.myDatabaseServer;
import javax.swing.*;
import java.util.*;
import java.io.*;
import java.io.InputStream;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Jermaine H. Ramsay
 */
public class ProgramUpdates extends GlobalFunctions {
     private static String myVersion = getVersion();
     private static Updater myUpdater = new Updater();
     private static String newUpdateVersion;
    
    /**
     * Creates new form ProgramUpdates
     */
    public ProgramUpdates() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Ramil Rx System Updates");
        txtCurrentVersion.setText(myVersion);
        txtUpdatedVersion.setText(newUpdateVersion);
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblCurrentVersion = new javax.swing.JLabel();
        txtUpdatedVersion = new javax.swing.JTextField();
        lblUpdatedVersion = new javax.swing.JLabel();
        txtCurrentVersion = new javax.swing.JTextField();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        lblTitle.setText("Program Updater");

        lblCurrentVersion.setText("Current App Version:");

        txtUpdatedVersion.setEditable(false);
        txtUpdatedVersion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUpdatedVersion.setBorder(null);
        txtUpdatedVersion.setEnabled(false);
        txtUpdatedVersion.setFocusable(false);

        lblUpdatedVersion.setText("Updated App Version:");

        txtCurrentVersion.setEditable(false);
        txtCurrentVersion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCurrentVersion.setBorder(null);
        txtCurrentVersion.setEnabled(false);
        txtCurrentVersion.setFocusable(false);
        txtCurrentVersion.setRequestFocusEnabled(false);

        btnClose.setBackground(new java.awt.Color(242, 242, 242));
        btnClose.setText("Close");
        btnClose.setBorder(null);
        btnClose.addActionListener(this::btnCloseActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblUpdatedVersion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUpdatedVersion, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblTitle)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblCurrentVersion)
                            .addGap(18, 18, 18)
                            .addComponent(txtCurrentVersion, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(175, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCurrentVersion)
                    .addComponent(txtCurrentVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUpdatedVersion)
                    .addComponent(txtUpdatedVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // Close Button.
        this.setVisible(false);
        myPharmSuite.setVisible(true);
        
    }//GEN-LAST:event_btnCloseActionPerformed

    // Functions.
    
    // Function get appVersion.
    private static String getVersion() {
         Properties properties = new Properties();
        // Load the file from the classpath
        try (InputStream input = GlobalVariables.class.getResourceAsStream("/config.properties")) {
            
            if (input == null) {
                return "Unknown (properties missing)";
            }
            
            properties.load(input);
            return properties.getProperty("app.version", "Unknown");
            
        } catch (IOException ex) {
            ex.printStackTrace();
            return "Unknown (error loading)";
        }
        
    }
    // Function to read files on github

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JLabel lblCurrentVersion;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUpdatedVersion;
    private javax.swing.JTextField txtCurrentVersion;
    private javax.swing.JTextField txtUpdatedVersion;
    // End of variables declaration//GEN-END:variables
}
